spring:
  application:
    name: WeChat-Study
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      indent-output: true
server:
  port: 443
  servlet:
    context-path: /weChat
weChat:
  appID: wxe47b76b52b3989d9
  appsecret: 5c659c07fbb51ee93c84675e7353e00c
  #  appID: wx13074d057e9f41cd
  #  appsecret: 249b733fef03cbb535d2c679b99808f2
  accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s